name: "Reusable Secret Scan"
description: "Scans for secrets using TruffleHog"

on:
  workflow_call:
    inputs:
      base:
        description: "Base branch to scan from (usually main)"
        default: "main"
        type: string
      head:
        description: "Head branch to scan (usually HEAD)"
        default: "HEAD"
        type: string

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.82.7
        with:
          path: ./
          base: ${{ inputs.base }}
          head: ${{ inputs.head }}
          extra_args: --debug --only-verified
